# Generated by Django 2.0.5 on 2018-06-04 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0003_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='enddate',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
