# Generated by Django 2.0.5 on 2018-06-05 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0007_auto_20180605_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(regex='^[АВЕКМНОРСТУХ][0-9]{3}[АВЕКМНОРСТУХ]{2}[0-9]{0, 3}')]),
        ),
    ]
