# Generated by Django 2.0.5 on 2018-06-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0009_auto_20180605_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='endpoint_coordinate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_crd', to='carpark.Point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='startpoint_coordinate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strt_crd', to='carpark.Point'),
            preserve_default=False,
        ),
    ]
